name: Website Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq and curl
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Write config from secret
        run: echo '${{ secrets.MONITOR_CONFIG_JSON }}' > config.json

      - name: Run monitor script
        run: |
          chmod +x monitor.sh
          ./monitor.sh
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Commit and push changes
        run: |
          git config --global user.name "monitor-bot"
          git config --global user.email "monitor@github.com"
          git add status.json logs/
          git commit -m "🤖 更新监控状态 $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
